apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key | quote }}
  DB_PASSWORD: {{ .Values.mysql.auth.password | quote }}
