apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomopensource.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_KEY: {{ required "app.key is required" .Values.app.key | quote }}
  DB_PASSWORD: {{ required "mysql.auth.password is required" .Values.mysql.auth.password | quote }}
