apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pomopensource.labels" . | nindent 4 }}
  name: {{ include "pomopensource.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "pomopensource.selectorLabels" . | nindent 4 }}
  type: ClusterIP
